parameters:
  _param:
    docker_postgresql_replicas: 1
    postgresql_bind_host: postgresql-db
    postgresql_bind_port: 5432
    postgresql_exposed_port: 5432
    postgresql_ssl:
      enabled: false
    postgresql_admin_user: postgres
  docker:
    client:
      stack:
        postgresql:
          environment:
            POSTGRES_USER: ${_param:postgresql_admin_user}
            POSTGRES_PASSWORD: ${_param:postgresql_admin_user_password}
            PGDATA: /var/lib/postgresql/data/pgdata
          service:
            postgresql-db:
              image: ${_param:docker_image_postgresql}
              deploy:
                replicas: ${_param:docker_postgresql_replicas}
                restart_policy:
                  condition: any
              volumes:
                - /srv/volumes/postgresql/data:/var/lib/postgresql/data
              ports:
                - ${_param:postgresql_exposed_port}:${_param:postgresql_bind_port}
